[workspace]
members = [
        "datagen",
        "data-store",
        "hashjoin",
        "microbench",
        "numa-gpu",
        "radix-join",
        "sql-ops",
        "tpch-bench",
]

[profile.release]
debug = true
opt-level = 3

[profile.bench]
debug = true
opt-level = 3
