[package]
name = "numa-gpu"
version = "0.1.0"
authors = ["Clemens Lutz <lutzcle@cml.li>"]
license = "MPL-2.0"
repository = "https://github.com/TU-Berlin-DIMA/numa-gpu"
description = "Joins and morsel-driven parallelism using NVLink 2.0 on POWER9"
readme = "README.md"

[dependencies]
# accel = { path = "../accel" }
accel = { git = "https://github.com/LutzCle/accel.git" }
accel-native = { git = "https://github.com/lutzcle/accel-native" }
cuda-sys = { git = "https://github.com/LutzCle/accel.git" }
error-chain = "~0.12.0"
mchj-generator = { git = "https://github.com/LutzCle/mchj-generator.git" }

[dev-dependencies]
average = "~0.9.2"
csv = "~1.0.1"
hostname = "~0.1.5"
serde = "~1.0.76"
serde_derive = "~1.0.76"

[profile.release]
debug = true
opt-level = 3

[profile.bench]
debug = true
opt-level = 3

[[bench]]
name = "hash_join"
harness = false
