[package]
name = "microbench"
version = "0.1.0"
authors = ["Clemens Lutz <lutzcle@cml.li>"]
description = "Performance microbenchmarks for NVLink 2.0 on POWER9"
readme = "../README.md"
links = "numa"
edition = "2018"

[dependencies]
accel = { git = "https://github.com/LutzCle/accel.git" }
average = "~0.9.2"
clap = "~2.32.0"
structopt = "0.2.13"
csv = "~1.0.1"
cuda-sys = { git = "https://github.com/LutzCle/accel.git" }
hostname = "~0.1.5"
libc = "~0.2.43"
nvml-wrapper = "~0.4.0"
serde = "~1.0.76"
serde_derive = "~1.0.76"
rayon = "~1.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
raw-cpuid = "~6.1.0"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
